apiVersion: v1 
kind: Secret
metadata:
  name: mysql-secret
  namespace: petclinic
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== #echo -n 'root' | base64
  MYSQL_PASSWORD: cGV0Y2xpbmlj #echo -n 'petclinic' | base64