apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
spec:
  replicas: 4
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels: 
        app: petclinic 
    spec:
      containers:
        - name: petclinic
          image: sid3121997/petclinic-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.petclinic.svc.cluster.local:3306/petclinic
            - name: SPRING_DATASOURCE_USERNAME
              value: petclinic 
            - name: SPRING_DATASOURCE_PASSWORD
              value: petclinic
          resources:
            requests:
              cpu: "300m" 
              memory: "200Mi" 
            limits:
              cpu: "500m" 
              memory: "300Mi" 

---
apiVersion: v1 
kind: Service 
metadata:
  name: petclinic
  namespace: petclinic
spec: 
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: petclinic